# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('agent', models.CharField(max_length=11)),
                ('created_dt', models.DateTimeField()),
            ],
        ),
    ]
