# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='StoreB2B',
        ),
    ]
