# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_auto_20171201_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentB2B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=11)),
                ('full_name', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=11)),
            ],
        ),
    ]
