# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_agentb2b'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeb2b',
            old_name='agent',
            new_name='agent_num',
        ),
        migrations.AddField(
            model_name='storeb2b',
            name='agent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
