# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('superCode', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['superCode', 'code'],
            },
        ),
    ]
