# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=100)),
                ('superCode', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['superCode', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('code', models.CharField(max_length=3)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['type', 'code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='enumeration',
            unique_together=set([('type', 'code')]),
        ),
    ]
