# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sale_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateField(auto_now_add=True)),
                ('salesname', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('imageurl', models.CharField(max_length=256)),
                ('checkif', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sale_upload',
            },
        ),
    ]
